spring:
  datasource: # H2 DB 설정
    url: jdbc:h2:mem:JPATest
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true # H2 DB 웹콘솔 사용하도록 설정 (http://localhost:8080/h2-console)
      path: /h2-console
  jpa:
    database: H2
    show-sql: true # Jpa 수행 시 SQL문 로그 출력
    properties:
      hibernate:
        "[format_sql]": true # 쿼리 출력시 포맷 정렬되도록 설정
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true #JSP수정시 서버 재시작없이 바로 적용될 수 있게 설정

# logging.level:
#   org.hibernate.SQL: debug